# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clash Royale Arena
email: admin@clashroyalearena.site
description: > # this means to ignore newlines until "baseurl:"
  Clash Royale Arena is a blog dedicated to bringing you the best deck combinations for every arena in Clash Royale Game.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.clashroyalearena.site" # the base hostname & protocol for your site
twitter_username: sjbuzzika
github_username:  satyawrat

# Build settings
markdown: kramdown
